service.qa.upstream_name=agent-business-solution
service.qa.invoke_url=http://127.0.0.1:8002/invoke

service.compliance.upstream_name=atomic-ai-service
service.compliance.invoke_url=http://127.0.0.1:8003/invoke

service.pricing.upstream_name=agent-model-runtime
service.pricing.invoke_url=http://127.0.0.1:8081/invoke
